// POST LOADING
export const MEET_LOADING_REQUEST = "MEET_LOADING_REQUEST";
export const MEET_LOADING_SUCCESS = "MEET_LOADING_SUCCESS";
export const MEET_LOADING_FAILURE = "MEET_LOADING_FAILURE";
// CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";
