// CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

// MEMBER REGISTER
export const MEMBER_REGISTER_REQUEST = "MEMBER_REGISTER_REQUEST";
export const MEMBER_REGISTER_SUCCESS = "MEMBER_REGISTER_SUCCESS";
export const MEMBER_REGISTER_FAILURE = "MEMBER_REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// MEMBER LOADING
export const MEMBER_LOADING_REQUEST = "MEMBER_LOADING_REQUEST";
export const MEMBER_LOADING_SUCCESS = "MEMBER_LOADING_SUCCESS";
export const MEMBER_LOADING_FAILURE = "MEMBER_LOADING_FAILURE";

// MEET CREATE
export const MEET_CREATE_REQUEST = "MEETING_CREATE_REQUEST";
export const MEET_CREATE_SUCCESS = "MEETING_CREATE_SUCCESS";
export const MEET_CREATE_FAILURE = "MEETING_CREATE_FAILURE";

// MEET LOADING
export const MEET_LOADING_REQUEST = "MEET_LOADING_REQUEST";
export const MEET_LOADING_SUCCESS = "MEET_LOADING_SUCCESS";
export const MEET_LOADING_FAILURE = "MEET_LOADING_FAILURE";

// MEET DETAIL LOADING
export const MEET_DETAIL_LOADING_REQUEST = "MEET_DETAIL_LOADING_REQUEST";
export const MEET_DETAIL_LOADING_SUCCESS = "MEET_DETAIL_LOADING_SUCCESS";
export const MEET_DETAIL_LOADING_FAILURE = "MEET_DETAIL_LOADING_FAILURE";

// MEET JOIN
export const MEET_JOIN_REQUEST = "MEETING_JOIN_REQUEST";
export const MEET_JOIN_SUCCESS = "MEETING_JOIN_SUCCESS";
export const MEET_JOIN_FAILURE = "MEETING_JOIN_FAILURE";

// MEET MINE LOADING
export const MEET_MINE_LOADING_REQUEST = "MEET_MINE_LOADING_REQUEST";
export const MEET_MINE_LOADING_SUCCESS = "MEET_MINE_LOADING_SUCCESS";
export const MEET_MINE_LOADING_FAILURE = "MEET_MINE_LOADING_FAILURE";

// MEET DELETE
export const MEET_DELETE_REQUEST = "MEET_DELETE_REQUEST";
export const MEET_DELETE_SUCCESS = "MEET_DELETE_SUCCESS";
export const MEET_DELETE_FAILURE = "MEET_DELETE_FAILURE";

// MEET APPROVE
export const MEET_APPROVE_REQUEST = "MEET_APPROVE_REQUEST";
export const MEET_APPROVE_SUCCESS = "MEET_APPROVE_SUCCESS";
export const MEET_APPROVE_FAILURE = "MEET_APPROVE_FAILURE";
